### ISSUE TITLE
Failed to load plugin "kigen-ac_redux.smx": Unable to load plugin (bad header).

### ISSUE THREAD

**Issue by onlybacon** [DJPlaya/Kigen-AC-Redux#53]
**Game**
CS:S

**SourceMod Version**
1.12

**Describe the Bug**
Failed to load plugin "kigen-ac_redux.smx": Unable to load plugin (bad header).

**To Reproduce**
Start the server with kigen-ac_redux.smx in /plugins/

**kacr_status output**
Unknown command "kacr_status"

**Additional**
Maybe I am missing a requirement?

**Comment by DJPlaya** [comment]
Sorry for the lack of maintenance despite the project readme stating "Maintained".
The KACR version hosted here was build for Sourcemod 1.10, the error confirms that.
I have updated the code to compile on 1.12 and did minimal testing in TF2.
Please report if you experience problems on movement heavy servers like surf or  bhop.
It is to be said that the current version of KACR features mostly basic protection. It is advised to use flood prevention and a different system like lilac for aimbots and optimizers.

**Comment by onlybacon** [comment]
Hi, I still get the same error message. Is it because I am supposed to run spcomp.exe?

**Comment by Nerus87** [comment]
You should always build the last code, no matter if the developer provided the smx in the release.
I believe any of the plugins should be provided without compiled files to avoid those situations.

**Comment by onlybacon** [comment]
thank you, compile.bat works.
